# Generated by Django 4.0.6 on 2022-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sportwear', 'Sportwear'), ('Outwear', 'Outwear')], max_length=10),
        ),
    ]
