# Generated by Django 4.0.6 on 2022-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
