# Generated by Django 4.0.6 on 2022-07-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slug',
            new_name='product_code',
        ),
    ]
