# Generated by Django 4.0.6 on 2022-07-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_product_code_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slug',
            new_name='product_code',
        ),
    ]
