# Generated by Django 4.0.6 on 2022-07-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_slug_item_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_code',
            new_name='slug',
        ),
    ]
