# Generated by Django 4.0.6 on 2022-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_item_discount_alter_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
