# Generated by Django 4.0.6 on 2022-07-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_item_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description2',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
