# Generated by Django 4.0.6 on 2022-07-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
    ]
