# Generated by Django 4.0.6 on 2022-07-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
    ]
